### PR TITLE
Adding VCS repository file

### PR DESCRIPTION
**Pull request by bsb808**
### Summary

This PR adds the `repos.txt` file to use with the vcs tool for setting up and maintaining the source repositories for the project.

### Test

Follow the setup wiki: https://github.com/Field-Robotics-Lab/optical_swarm/wiki/workspace_setup  to use the file to clone all the required repos.

### Known issues

Still need to add the april tag repos to the VCS list - see #2

### CODE REVIEW

**Comment by matthewheubach** [comment]
@bsb808 
 I had some issues with the vcs import tool using the previous steps on the wiki, namely with the file type. I changed the repos.txt to repos.yaml based on the vcs import documentation I found and added the missing repositories. Using the updated [wiki instructions](https://github.com/Field-Robotics-Lab/optical_swarm/wiki/workspace_setup) should now successfully clone the necessary repositories and execute the catkin_make_isolated command without issue.

**Comment by bsb808** [comment]
Great.  If you are happy with that change, go ahead and approve - then I'll merge.

**Comment by matthewheubach** [comment]
I went ahead and removed the repos.txt as it is no longer needed.

**Review by matthewheubach — APPROVED** [review]
Changes approved. Branch is ready to merge and close.

**Pull request merged**
